name: Test and Deploy Workflow

inputs:
  env_aws_secret_name:
    required: true
    type: string
  script_path:
    type: string
  auth_stack_name:
    type: string
  dir:
    required: false
    type: string
    default: "."
  skip_tests:
    required: false
    type: boolean
    default: false

runs:
  using: "composite"
  steps:

    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

    - name: Set up uv
      uses: astral-sh/setup-uv@fac544c07dec837d0ccb6301d7b5580bf5edae39 # v8.2.0
      with:
        enable-cache: true

    - name: Install python dependencies
      working-directory: ${{ inputs.dir }}
      shell: bash
      run: |
        make install

     # === Only run these steps if skip_tests is false ===

    - name: Launch services
      if: ${{ inputs.skip_tests == false }}
      shell: bash
      working-directory: ${{ inputs.dir }}
      run: docker compose up --build -d

    - name: Wait for STAC API to be ready
      if: ${{ inputs.skip_tests == false }}
      shell: bash
      working-directory: ${{ inputs.dir }}
      run: |
        echo "Waiting for STAC API to be available at localhost:8081..."
        timeout 120 bash -c 'until curl -f http://localhost:8081/api/stac/_mgmt/ping 2>/dev/null; do sleep 0.25; done'
        echo "STAC API is ready!"

    - name: Integrations tests
      if: ${{ inputs.skip_tests == false }}
      shell: bash
      working-directory: ${{ inputs.dir }}
      run: uv run pytest .github/workflows/tests/ -vv -s

    - name: Stop services
      if: ${{ inputs.skip_tests == false }}
      shell: bash
      working-directory: ${{ inputs.dir }}
      run: |
        docker compose down --rmi all --volumes
        sudo rm -rf .pgdata

    # ===================================================

    - name: Get relevant environment configuration from aws secrets
      shell: bash
      working-directory: ${{ inputs.dir }}
      env:
        AWS_DEFAULT_REGION: us-west-2
      run: |
        if [ -z "${{ inputs.script_path }}" ]
          then
            ./scripts/sync-env-local.sh ${{ inputs.env_aws_secret_name }}
          else
            uv run ${{ inputs.script_path }} --secret-id ${{ inputs.env_aws_secret_name }} --stack-names ${{ inputs.auth_stack_name }}
        fi

    - name: Deploy
      shell: bash
      working-directory: ${{ inputs.dir }}
      run: |
        make deploy ARGS="--require-approval never"
