name: Deploy

inputs:
  env_aws_secret_name:
    required: true
    type: string
  dir:
    required: false
    type: string
    default: "."
  project_prefix:
    type: string
  stage:
    type: string
  script_path:
    type: string



runs:
  using: "composite"
  steps:

    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Setup Node
      uses: actions/setup-node@v3
      with: 
        node-version: 17

    - uses: actions/cache@v3
      with:
        path: ~/.npm
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
    
    - name: Install CDK
      shell: bash
      run: npm install -g aws-cdk@2

    - uses: actions/cache@v3
      with:
        path: ${{ env.pythonLocation }}
        key:  ${{ env.pythonLocation }}-${{ hashFiles('${{ inputs.dir }}/setup.py') }}
    
    - name: Install python dependencies
      shell: bash
      working-directory: ${{ inputs.dir }}
      run: |
        python -m pip install --upgrade pip
        python -m pip install -e .[dev,deploy,test] 
        python -m pip install boto3

    - name: Get relevant environment configuration from aws secrets
      shell: bash
      working-directory: ${{ inputs.dir }}
      env:
        AWS_DEFAULT_REGION: us-west-2
      run: |
        if [ -z "${{ inputs.script_path }}" ]
          then
            ./scripts/sync-env-local.sh ${{ inputs.env_aws_secret_name }}
          else
            python ${{ inputs.script_path }} --secret-id ${{ inputs.env_aws_secret_name }}
            echo "PROJECT_PREFIX=${{ inputs.project_prefix }}" >> .env
            echo "STAGE=${{ inputs.stage }}" >> .env
        fi
        

    - name: Deploy 
      shell: bash
      working-directory: ${{ inputs.dir }}
      run: |
        cdk deploy --all --require-approval never --outputs-file ${HOME}/cdk-outputs.json
