name: Release Workflow

permissions:
  id-token: write
  contents: read

on:
  push:
    branches:
    - develop
    - main

jobs:
    release:
        runs-on: ubuntu-latest
        concurrency: release
        permissions:
          id-token: write
          contents: write

        steps:
        - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
          with:
            fetch-depth: 0
        - name: Python Semantic Release
          uses: python-semantic-release/python-semantic-release@26bb37cfab71a5a372e3db0f48a6eac57519a4a6 #v9.21.0
          with:
            changelog: "false"
            github_token: ${{ secrets.GITHUB_TOKEN }}