name: Release Workflow

permissions:
  contents: read

on:
  push:
    branches:
    - develop

jobs:
    release:
        runs-on: ubuntu-latest
        concurrency: release
        permissions:
          id-token: write
          contents: write

        steps:
        - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
          with:
            fetch-depth: 0
        - name: Python Semantic Release
          uses: python-semantic-release/python-semantic-release@39dd2052f2ce8282a5d932c31d58a2ca06d2550e # v10.6.1
          with:
            changelog: "false"
            github_token: ${{ secrets.GITHUB_TOKEN }}